# Generated by Django 3.0.7 on 2020-06-22 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_author', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_book', models.CharField(max_length=255)),
                ('publishingYear', models.DateTimeField()),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_management.Author')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'card',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_category', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='PublishingCompany',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_company', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'publishing_company',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_staff', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Readers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_readers', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_management.Card')),
            ],
            options={
                'db_table': 'readers',
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('borrow_date', models.DateTimeField()),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_management.Card')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_management.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='LoanDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('have_paid', models.BooleanField(null=True)),
                ('pay_day', models.DateTimeField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_management.Book')),
                ('loanPayment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_management.LoanPayment')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_management.Category'),
        ),
        migrations.AddField(
            model_name='book',
            name='publishingCompany_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_management.PublishingCompany'),
        ),
    ]
