# Generated by Django 3.0.7 on 2020-06-22 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loandetails',
            table='loan_details',
        ),
        migrations.AlterModelTable(
            name='loanpayment',
            table='loan_payment',
        ),
        migrations.AlterModelTable(
            name='staff',
            table='staff',
        ),
    ]
