# Generated by Django 3.0.7 on 2020-06-24 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0002_auto_20200622_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='category_id',
            new_name='category',
        ),
    ]
