# Generated by Django 3.0.7 on 2020-06-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0006_auto_20200626_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
